### ISSUE TITLE
db_bc_deduct_value in database.py, value can be negative

### ISSUE THREAD

**Issue by jzhang866** [IvoryCandy/MARTA-Passenger-Traffic#22]
testing db_bc_deduct_value(), after deduction, the card value be -0.5, and no error was shown

**Comment by soapisnotfat** [comment]
MySQL does not support the SQL CHECK constraint. Please use your front-end to check your input if you decided to do the heavy weight.

**Comment by jzhang866** [comment]
bc add value and change value, station update fare and create station check whether the return value is 1000.

**Comment by soapisnotfat** [comment]
def bc_change_value(num, value):
def bc_add_value(num, value):
def station_update_fare(stopID, fare):
def insert_station(stopid, name, enterFare, ClosedStatus, isTrain, intersection=None):
return 1000 - handle required
